CREATE DATABASE mybatisDB;
 USE mybatisDB;
SELECT DATABASE();


CREATE TABLE `Person` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) DEFAULT NULL COMMENT '姓名',
  `gender` VARCHAR(10) DEFAULT NULL COMMENT '性别',
  `mobilephone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  PRIMARY KEY  (`id`)
);
INSERT INTO Person VALUES('1','章静芳','女','13726741987');
INSERT INTO Person VALUES('2','徐乐','男','18782242228');
INSERT INTO Person VALUES('3','杨慧芳','女','13646218594');

SELECT * FROM person;